"""
APOS — A Precise Ontology System for AI agents.

Provides semantic layer, governance, and context management for AI-driven applications.
"""

from pathlib import Path
from typing import Optional

__version__ = "0.1.0-beta"
__author__ = "Jader Greiner"
__author_email__ = "jadergreiner@gmail.com"
__license__ = "Proprietary"

# Metadata that identifies a project as one that has adopted APOS.
APOS_PROJECT_METADATA = {
    "framework": "apos",
    "framework_version": __version__,
    "marker_file": "BOOTSTRAP_GATE.md",
}


def is_apos_project(project_root: Optional[Path] = None) -> bool:
    """Detect whether a directory is a project that has bootstrapped APOS.

    A project is considered an APOS project once it has BOOTSTRAP_GATE.md,
    generated by `python -m apos init`.
    """
    root = project_root or Path.cwd()
    return (root / APOS_PROJECT_METADATA["marker_file"]).exists()


from apos.core import (  # noqa: E402
    KnowledgeGraph,
    Node,
    NodeType,
    NodeMetadata,
    Edge,
    EdgeType,
    EdgeMetadata,
    make_urn,
    parse_urn,
    is_valid_urn,
)
from apos.bootstrap import (  # noqa: E402
    BootstrapGate,
    FoundationDefinitionSession,
    SessionManager,
    matches_session_trigger,
)
from apos.kernel import (  # noqa: E402
    CommitTrackingValidator,
    CommitTrackingResult,
)
from apos.project_adapter import (  # noqa: E402
    ProjectAdapter,
    ProjectProfile,
)

__all__ = [
    "__version__",
    "APOS_PROJECT_METADATA",
    "is_apos_project",
    "KnowledgeGraph",
    "Node",
    "NodeType",
    "NodeMetadata",
    "Edge",
    "EdgeType",
    "EdgeMetadata",
    "make_urn",
    "parse_urn",
    "is_valid_urn",
    "BootstrapGate",
    "FoundationDefinitionSession",
    "SessionManager",
    "matches_session_trigger",
    "CommitTrackingValidator",
    "CommitTrackingResult",
    "ProjectAdapter",
    "ProjectProfile",
]
