"""BootstrapGateV2 — integrates ProjectAdapter with BootstrapGate.

Uses ProjectProfile to validate foundations and auto-generate APOS_CONFIG.yaml.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Union

import yaml

from apos.project_adapter import ProjectAdapter, ProjectProfile


@dataclass
class GateResultV2:
    """Result of BootstrapGateV2 validation."""

    passed: bool
    score: float  # 0.0 to 1.0
    issues: list[str]  # items that blocked
    warnings: list[str]  # items that did not block but deserve attention


class BootstrapGateV2:
    """
    Gate 2.0 that uses ProjectProfile (via ProjectAdapter) to validate
    semantic foundations and auto-generate APOS_CONFIG.yaml.

    Accepts either a pre-built ProjectProfile or a ProjectAdapter (which
    will run discover() on the given project_root).
    """

    MIN_CONFIDENCE: float = 0.5

    def __init__(
        self,
        profile: Optional[ProjectProfile] = None,
        adapter: Optional[ProjectAdapter] = None,
        project_root: Optional[Union[str, Path]] = None,
    ) -> None:
        """
        BootstrapGateV2 requires one of:
          - profile: a pre-built ProjectProfile
          - adapter + project_root: run adapter.discover() on project_root

        If both are provided, 'profile' takes precedence.
        """
        self._project_root: Optional[Path] = None

        if profile is not None:
            self._profile = profile
            return

        if adapter is not None and project_root is not None:
            root = Path(project_root)
            self._profile = adapter.discover(root)
            self._project_root = root
            return

        raise ValueError(
            "Must provide either 'profile' or ('adapter' + 'project_root')"
        )

    @property
    def profile(self) -> ProjectProfile:
        """The resolved ProjectProfile."""
        return self._profile

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def validate(self) -> GateResultV2:
        """
        Validate foundations using the ProjectProfile.

        Rules:
          - language == "unknown"          → issue (blocker)
          - module_count == 0              → warning (few modules)
          - has_ontology == False           → warning (no docs/SDD/)
          - confidence < MIN_CONFIDENCE     → issue (blocker)

        Returns GateResultV2 with passed, score, issues, warnings.
        """
        issues: list[str] = []
        warnings: list[str] = []

        p = self._profile

        # --- language check (blocker) ---
        if p.language == "unknown":
            issues.append("Language could not be detected (project may be empty or misconfigured)")
        else:
            # When language IS detected, it's a positive contributor
            pass

        # --- module_count check (warning) ---
        if p.module_count == 0:
            warnings.append(
                "No modules found — project may be too small or detection incomplete"
            )

        # --- ontology check (warning) ---
        if not p.has_ontology:
            warnings.append(
                "No ontology detected (docs/SDD/ directory not found)"
            )

        # --- confidence check (blocker) ---
        confidence = self._compute_confidence()
        if confidence < self.MIN_CONFIDENCE:
            issues.append(
                f"Confidence score ({confidence:.2f}) is below minimum ({self.MIN_CONFIDENCE})"
            )

        score = confidence
        passed = len(issues) == 0

        return GateResultV2(
            passed=passed,
            score=score,
            issues=issues,
            warnings=warnings,
        )

    def generate_config(self) -> str:
        """Generate APOS_CONFIG.yaml content from profile."""
        p = self._profile
        config = {
            "# APOS Configuration — auto-generated by BootstrapGateV2": None,
            "project": {
                "language": p.language,
                "framework": p.framework,
                "database": p.database,
                "cloud_provider": p.cloud_provider,
            },
            "ontology": {
                "has_ontology": p.has_ontology,
                "domain_entities": p.domain_entities,
            },
            "governance": {
                "confidence_score": self._compute_confidence(),
                "min_confidence": self.MIN_CONFIDENCE,
            },
        }
        return yaml.dump(config, default_flow_style=False, sort_keys=False)

    def save_config(self, path: Union[str, Path] = "APOS_CONFIG.yaml") -> str:
        """Save APOS_CONFIG.yaml to disk and return the file path."""
        content = self.generate_config()
        target = Path(path)
        target.write_text(content, encoding="utf-8")
        return str(target.resolve())

    def report(self) -> str:
        """Return a human-readable summary of the profile and validation."""
        p = self._profile
        result = self.validate()
        lines: list[str] = []
        lines.append("=" * 60)
        lines.append("  BootstrapGateV2 — Project Profile Report")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"  Language:       {p.language}")
        lines.append(f"  Framework:      {p.framework}")
        lines.append(f"  Database:       {p.database}")
        lines.append(f"  Cloud Provider: {p.cloud_provider}")
        lines.append(f"  Module Count:   {p.module_count}")
        lines.append(f"  Has Ontology:   {p.has_ontology}")
        lines.append(f"  Domain Entities:{' ' + ', '.join(p.domain_entities) if p.domain_entities else ' (none)'}")
        lines.append("")
        lines.append(f"  Confidence:     {result.score:.2f} / 1.00")
        lines.append(f"  Gate Result:    {'✅ PASSED' if result.passed else '❌ FAILED'}")
        lines.append("")

        if result.issues:
            lines.append("  Issues (blocking):")
            for i in result.issues:
                lines.append(f"    ❌ {i}")
            lines.append("")

        if result.warnings:
            lines.append("  Warnings (non-blocking):")
            for w in result.warnings:
                lines.append(f"    ⚠️  {w}")
            lines.append("")

        lines.append("=" * 60)
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _compute_confidence(self) -> float:
        """
        Calculate confidence score (0.0–1.0) from ProjectAdapter's
        internal calculation, or fallback to a simple heuristic.
        """
        try:
            return ProjectAdapter()._calculate_confidence(self._profile)
        except Exception:
            return self._fallback_confidence()

    def _fallback_confidence(self) -> float:
        """Simple heuristic fallback."""
        p = self._profile
        total = 0
        filled = 0

        total += 1
        if p.language != "unknown":
            filled += 1

        total += 1
        if p.framework != "unknown":
            filled += 1

        total += 1
        if p.database != "unknown":
            filled += 1

        total += 1
        if p.module_count > 0:
            filled += 1

        total += 1
        if len(p.architecture_patterns) > 0:
            filled += 1

        total += 1
        if p.has_ontology:
            filled += 1

        return round(filled / total, 2) if total > 0 else 0.0
